name: Build Armbian

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        board:
          - orangepi-r1
          - orangepizero

    runs-on: ubuntu-24.04

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Check disk space
        run: df -h

      - name: Checkout Armbian
        uses: actions/checkout@v4

      - name: Build Armbian
        run: |
          ./compile.sh \
            BOARD="${{ matrix.board }}" \
            BRANCH=current \
            RELEASE=bookworm \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no \
            KERNEL_CONFIGURE=no \
            COMPRESS_OUTPUTIMAGE=xz

      - name: Check disk space after build
        if: always()
        run: df -h

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: armbian-${{ matrix.board }}-bookworm
          path: output/images/*
          if-no-files-found: error
